#ifndef __ICALLS_H
#define __ICALLS_H


#include <godot.h>


#include "core/CoreTypes.hpp"
#include "Object.hpp"


using namespace godot;


void ___godot_icall_void_int_Object_int(godot_method_bind *mb, godot_object *inst, const int , const Object *, const int );
InputEvent ___godot_icall_InputEvent(godot_method_bind *mb, godot_object *inst);
String ___godot_icall_String_String(godot_method_bind *mb, godot_object *inst, const String& );
Error ___godot_icall_Error_Object_String_Variant_int(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const Variant& , const int );
Vector2 ___godot_icall_Vector2_String(godot_method_bind *mb, godot_object *inst, const String& );
float ___godot_icall_float_int(godot_method_bind *mb, godot_object *inst, const int );
bool ___godot_icall_bool_Object(godot_method_bind *mb, godot_object *inst, const Object *);
Array ___godot_icall_Array_NodePath(godot_method_bind *mb, godot_object *inst, const NodePath& );
void ___godot_icall_void_Vector3_Vector3_Vector3_int(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Vector3& , const int );
void ___godot_icall_void_Vector2_bool(godot_method_bind *mb, godot_object *inst, const Vector2& , const bool );
void ___godot_icall_void_RID_Object_String(godot_method_bind *mb, godot_object *inst, const RID& , const Object *, const String& );
Array ___godot_icall_Array_float_float_int_int(godot_method_bind *mb, godot_object *inst, const float , const float , const int , const int );
void ___godot_icall_void_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& );
float ___godot_icall_float_RID_int_int(godot_method_bind *mb, godot_object *inst, const RID& , const int , const int );
Dictionary ___godot_icall_Dictionary_bool(godot_method_bind *mb, godot_object *inst, const bool );
void ___godot_icall_void_Object_Vector2_Color(godot_method_bind *mb, godot_object *inst, const Object *, const Vector2& , const Color& );
void ___godot_icall_void_int_Object_Vector2(godot_method_bind *mb, godot_object *inst, const int , const Object *, const Vector2& );
void ___godot_icall_void_Object_String_int(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const int );
int ___godot_icall_int_Object_int(godot_method_bind *mb, godot_object *inst, const Object *, const int );
void ___godot_icall_void_Vector2_float_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const float , const Vector2& );
float ___godot_icall_float_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
int ___godot_icall_int(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_Image(godot_method_bind *mb, godot_object *inst, const Image& );
void ___godot_icall_void_String_String_int(godot_method_bind *mb, godot_object *inst, const String& , const String& , const int );
void ___godot_icall_void_RID_Vector2_Color_bool(godot_method_bind *mb, godot_object *inst, const RID& , const Vector2& , const Color& , const bool );
Array ___godot_icall_Array_Object(godot_method_bind *mb, godot_object *inst, const Object *);
void ___godot_icall_void_PoolRealArray(godot_method_bind *mb, godot_object *inst, const PoolRealArray& );
Rect2 ___godot_icall_Rect2(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_RID_Rect2(godot_method_bind *mb, godot_object *inst, const RID& , const Rect2& );
int ___godot_icall_int_bool_bool(godot_method_bind *mb, godot_object *inst, const bool , const bool );
PoolColorArray ___godot_icall_PoolColorArray(godot_method_bind *mb, godot_object *inst);
Vector2 ___godot_icall_Vector2_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int );
int ___godot_icall_int_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int );
void ___godot_icall_void_Vector3_Vector3_Vector3_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Vector3& , const Vector3& , const Vector3& );
void ___godot_icall_void_int_float_float_float_bool(godot_method_bind *mb, godot_object *inst, const int , const float , const float , const float , const bool );
int ___godot_icall_int_PoolByteArray(godot_method_bind *mb, godot_object *inst, const PoolByteArray& );
int ___godot_icall_int_Dictionary(godot_method_bind *mb, godot_object *inst, const Dictionary& );
bool ___godot_icall_bool_String_String_int(godot_method_bind *mb, godot_object *inst, const String& , const String& , const int );
RID ___godot_icall_RID_RID_Vector3_RID_Vector3(godot_method_bind *mb, godot_object *inst, const RID& , const Vector3& , const RID& , const Vector3& );
void ___godot_icall_void_int_bool_int(godot_method_bind *mb, godot_object *inst, const int , const bool , const int );
Plane ___godot_icall_Plane_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_String_int_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int , const int );
int ___godot_icall_int_int_int_int_int(godot_method_bind *mb, godot_object *inst, const int , const int , const int , const int );
void ___godot_icall_void_Object(godot_method_bind *mb, godot_object *inst, const Object *);
void ___godot_icall_void_RID_int_int_bool(godot_method_bind *mb, godot_object *inst, const RID& , const int , const int , const bool );
void ___godot_icall_void_Transform(godot_method_bind *mb, godot_object *inst, const Transform& );
String ___godot_icall_String_PoolByteArray(godot_method_bind *mb, godot_object *inst, const PoolByteArray& );
void ___godot_icall_void_String_String_Object(godot_method_bind *mb, godot_object *inst, const String& , const String& , const Object *);
void ___godot_icall_void_Variant_Object(godot_method_bind *mb, godot_object *inst, const Variant& , const Object *);
Vector2 ___godot_icall_Vector2_float(godot_method_bind *mb, godot_object *inst, const float );
void ___godot_icall_void_int_Object_bool(godot_method_bind *mb, godot_object *inst, const int , const Object *, const bool );
void ___godot_icall_void_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
Vector3 ___godot_icall_Vector3_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
void ___godot_icall_void_String_String_Color(godot_method_bind *mb, godot_object *inst, const String& , const String& , const Color& );
void ___godot_icall_void_Object_bool(godot_method_bind *mb, godot_object *inst, const Object *, const bool );
RID ___godot_icall_RID_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
int ___godot_icall_int_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_int_Variant(godot_method_bind *mb, godot_object *inst, const int , const Variant& );
Vector2 ___godot_icall_Vector2_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
Transform ___godot_icall_Transform_RID(godot_method_bind *mb, godot_object *inst, const RID& );
Array ___godot_icall_Array_Array(godot_method_bind *mb, godot_object *inst, const Array& );
void ___godot_icall_void_RID_Rect2_Rect2_Color_bool(godot_method_bind *mb, godot_object *inst, const RID& , const Rect2& , const Rect2& , const Color& , const bool );
void ___godot_icall_void_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int );
void ___godot_icall_void_String_Variant_bool(godot_method_bind *mb, godot_object *inst, const String& , const Variant& , const bool );
void ___godot_icall_void_RID_int_float(godot_method_bind *mb, godot_object *inst, const RID& , const int , const float );
void ___godot_icall_void_int_Vector3_float(godot_method_bind *mb, godot_object *inst, const int , const Vector3& , const float );
NodePath ___godot_icall_NodePath_int_bool(godot_method_bind *mb, godot_object *inst, const int , const bool );
bool ___godot_icall_bool_Transform2D_Vector2_Object_Transform2D_Vector2(godot_method_bind *mb, godot_object *inst, const Transform2D& , const Vector2& , const Object *, const Transform2D& , const Vector2& );
Basis ___godot_icall_Basis(godot_method_bind *mb, godot_object *inst);
godot_object*  ___godot_icall_Object_Object_String(godot_method_bind *mb, godot_object *inst, const Object *, const String& );
Array ___godot_icall_Array_String(godot_method_bind *mb, godot_object *inst, const String& );
Variant ___godot_icall_Variant_Transform2D_Vector2_Object_Transform2D_Vector2(godot_method_bind *mb, godot_object *inst, const Transform2D& , const Vector2& , const Object *, const Transform2D& , const Vector2& );
void ___godot_icall_void_PoolStringArray_int(godot_method_bind *mb, godot_object *inst, const PoolStringArray& , const int );
int ___godot_icall_int_String_Object(godot_method_bind *mb, godot_object *inst, const String& , const Object *);
Array ___godot_icall_Array_int_float(godot_method_bind *mb, godot_object *inst, const int , const float );
void ___godot_icall_void_NodePath(godot_method_bind *mb, godot_object *inst, const NodePath& );
void ___godot_icall_void_RID_bool(godot_method_bind *mb, godot_object *inst, const RID& , const bool );
bool ___godot_icall_bool_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
Array ___godot_icall_Array_Object_Vector3(godot_method_bind *mb, godot_object *inst, const Object *, const Vector3& );
void ___godot_icall_void_Object_Object_int_bool(godot_method_bind *mb, godot_object *inst, const Object *, const Object *, const int , const bool );
PoolStringArray ___godot_icall_PoolStringArray_String_bool(godot_method_bind *mb, godot_object *inst, const String& , const bool );
int ___godot_icall_int_int_String_PoolStringArray_String(godot_method_bind *mb, godot_object *inst, const int , const String& , const PoolStringArray& , const String& );
void ___godot_icall_void_int_NodePath(godot_method_bind *mb, godot_object *inst, const int , const NodePath& );
PoolVector3Array ___godot_icall_PoolVector3Array_Vector3_Vector3_Array(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Array& );
godot_object*  ___godot_icall_Object_String_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int );
Rect2 ___godot_icall_Rect2_Object_int(godot_method_bind *mb, godot_object *inst, const Object *, const int );
void ___godot_icall_void_Color(godot_method_bind *mb, godot_object *inst, const Color& );
Vector2 ___godot_icall_Vector2(godot_method_bind *mb, godot_object *inst);
Variant ___godot_icall_Variant_Variant(godot_method_bind *mb, godot_object *inst, const Variant& );
Array ___godot_icall_Array_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
Variant ___godot_icall_Variant_Array_Array_int_Array(godot_method_bind *mb, godot_object *inst, const Array& , const Array& , const int , const Array& );
Vector3 ___godot_icall_Vector3(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_int_Object(godot_method_bind *mb, godot_object *inst, const int , const Object *);
void ___godot_icall_void_RID_RID_Transform(godot_method_bind *mb, godot_object *inst, const RID& , const RID& , const Transform& );
String ___godot_icall_String_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
void ___godot_icall_void_Rect3(godot_method_bind *mb, godot_object *inst, const Rect3& );
PoolRealArray ___godot_icall_PoolRealArray(godot_method_bind *mb, godot_object *inst);
godot_object*  ___godot_icall_Object_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
void ___godot_icall_void_RID_int_int_float(godot_method_bind *mb, godot_object *inst, const RID& , const int , const int , const float );
void ___godot_icall_void_bool(godot_method_bind *mb, godot_object *inst, const bool );
Color ___godot_icall_Color_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
void ___godot_icall_void_String_int_bool(godot_method_bind *mb, godot_object *inst, const String& , const int , const bool );
void ___godot_icall_void_String_int_Vector2(godot_method_bind *mb, godot_object *inst, const String& , const int , const Vector2& );
bool ___godot_icall_bool_String_Object_String(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const String& );
void ___godot_icall_void_RID_Vector2_String_Color_int(godot_method_bind *mb, godot_object *inst, const RID& , const Vector2& , const String& , const Color& , const int );
void ___godot_icall_void_PoolVector2Array_PoolColorArray_PoolVector2Array_Object(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& , const PoolColorArray& , const PoolVector2Array& , const Object *);
bool ___godot_icall_bool_NodePath(godot_method_bind *mb, godot_object *inst, const NodePath& );
void ___godot_icall_void(godot_method_bind *mb, godot_object *inst);
PoolVector3Array ___godot_icall_PoolVector3Array_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
bool ___godot_icall_bool_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int );
PoolVector3Array ___godot_icall_PoolVector3Array_Vector3_Vector3_Vector3_float(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Vector3& , const float );
void ___godot_icall_void_Object_Transform(godot_method_bind *mb, godot_object *inst, const Object *, const Transform& );
bool ___godot_icall_bool_RID_int_int(godot_method_bind *mb, godot_object *inst, const RID& , const int , const int );
void ___godot_icall_void_int_Object_int_bool(godot_method_bind *mb, godot_object *inst, const int , const Object *, const int , const bool );
float ___godot_icall_float_RID(godot_method_bind *mb, godot_object *inst, const RID& );
PoolVector3Array ___godot_icall_PoolVector3Array_Vector3_Vector3_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Vector3& , const Vector3& );
int ___godot_icall_int_bool(godot_method_bind *mb, godot_object *inst, const bool );
RID ___godot_icall_RID_RID_Transform_RID_Transform(godot_method_bind *mb, godot_object *inst, const RID& , const Transform& , const RID& , const Transform& );
float ___godot_icall_float_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
String ___godot_icall_String_Object(godot_method_bind *mb, godot_object *inst, const Object *);
PoolByteArray ___godot_icall_PoolByteArray(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_String_int_int_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int , const int , const int );
Array ___godot_icall_Array_PoolByteArray(godot_method_bind *mb, godot_object *inst, const PoolByteArray& );
Image ___godot_icall_Image_int(godot_method_bind *mb, godot_object *inst, const int );
bool ___godot_icall_bool_String(godot_method_bind *mb, godot_object *inst, const String& );
void ___godot_icall_void_Image_int(godot_method_bind *mb, godot_object *inst, const Image& , const int );
Transform2D ___godot_icall_Transform2D_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_Object_String_String(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const String& );
float ___godot_icall_float_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
void ___godot_icall_void_String_InputEvent(godot_method_bind *mb, godot_object *inst, const String& , const InputEvent& );
Dictionary ___godot_icall_Dictionary_Object(godot_method_bind *mb, godot_object *inst, const Object *);
void ___godot_icall_void_int_float(godot_method_bind *mb, godot_object *inst, const int , const float );
void ___godot_icall_void_float_Color(godot_method_bind *mb, godot_object *inst, const float , const Color& );
void ___godot_icall_void_int_bool_int_Color_bool_int_Color_Object_Object(godot_method_bind *mb, godot_object *inst, const int , const bool , const int , const Color& , const bool , const int , const Color& , const Object *, const Object *);
Image ___godot_icall_Image(godot_method_bind *mb, godot_object *inst);
godot_object*  ___godot_icall_Object_Object(godot_method_bind *mb, godot_object *inst, const Object *);
void ___godot_icall_void_String_Color(godot_method_bind *mb, godot_object *inst, const String& , const Color& );
godot_object*  ___godot_icall_Object_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
void ___godot_icall_void_RID_RID_Transform2D(godot_method_bind *mb, godot_object *inst, const RID& , const RID& , const Transform2D& );
int ___godot_icall_int_Object_Transform_Object(godot_method_bind *mb, godot_object *inst, const Object *, const Transform& , const Object *);
RID ___godot_icall_RID_int_bool(godot_method_bind *mb, godot_object *inst, const int , const bool );
bool ___godot_icall_bool_Object_float_String_Variant_Variant_Variant_Variant_Variant(godot_method_bind *mb, godot_object *inst, const Object *, const float , const String& , const Variant& , const Variant& , const Variant& , const Variant& , const Variant& );
Vector3 ___godot_icall_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
void ___godot_icall_void_int_PoolVector2Array(godot_method_bind *mb, godot_object *inst, const int , const PoolVector2Array& );
void ___godot_icall_void_Object_Vector2_String_Color_int(godot_method_bind *mb, godot_object *inst, const Object *, const Vector2& , const String& , const Color& , const int );
PoolVector3Array ___godot_icall_PoolVector3Array_Vector3_Vector3_bool(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const bool );
void ___godot_icall_void_Object_Rect2_bool_Color_bool(godot_method_bind *mb, godot_object *inst, const Object *, const Rect2& , const bool , const Color& , const bool );
InputEvent ___godot_icall_InputEvent_InputEvent(godot_method_bind *mb, godot_object *inst, const InputEvent& );
Array ___godot_icall_Array_String_bool(godot_method_bind *mb, godot_object *inst, const String& , const bool );
RID ___godot_icall_RID_RID(godot_method_bind *mb, godot_object *inst, const RID& );
bool ___godot_icall_bool_Transform2D_InputEvent(godot_method_bind *mb, godot_object *inst, const Transform2D& , const InputEvent& );
godot_object*  ___godot_icall_Object_float_bool(godot_method_bind *mb, godot_object *inst, const float , const bool );
void ___godot_icall_void_String_float_float_bool(godot_method_bind *mb, godot_object *inst, const String& , const float , const float , const bool );
int ___godot_icall_int_Vector2_bool(godot_method_bind *mb, godot_object *inst, const Vector2& , const bool );
void ___godot_icall_void_int_int_Variant(godot_method_bind *mb, godot_object *inst, const int , const int , const Variant& );
bool ___godot_icall_bool_Object_String(godot_method_bind *mb, godot_object *inst, const Object *, const String& );
void ___godot_icall_void_int_Vector3(godot_method_bind *mb, godot_object *inst, const int , const Vector3& );
NodePath ___godot_icall_NodePath_Object(godot_method_bind *mb, godot_object *inst, const Object *);
String ___godot_icall_String_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
void ___godot_icall_void_int_int_Object(godot_method_bind *mb, godot_object *inst, const int , const int , const Object *);
void ___godot_icall_void_int_String_Variant(godot_method_bind *mb, godot_object *inst, const int , const String& , const Variant& );
Error ___godot_icall_Error_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
PoolStringArray ___godot_icall_PoolStringArray_Object(godot_method_bind *mb, godot_object *inst, const Object *);
godot_object*  ___godot_icall_Object_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int );
void ___godot_icall_void_int_Object_String(godot_method_bind *mb, godot_object *inst, const int , const Object *, const String& );
RID ___godot_icall_RID_Vector2_Vector2_Vector2_RID_RID(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& , const RID& , const RID& );
void ___godot_icall_void_PoolVector2Array_int(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& , const int );
void ___godot_icall_void_String_String_Color_bool(godot_method_bind *mb, godot_object *inst, const String& , const String& , const Color& , const bool );
int ___godot_icall_int_int_float_Vector3_Quat_Vector3(godot_method_bind *mb, godot_object *inst, const int , const float , const Vector3& , const Quat& , const Vector3& );
void ___godot_icall_void_Object_float(godot_method_bind *mb, godot_object *inst, const Object *, const float );
int ___godot_icall_int_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
float ___godot_icall_float_Object_Vector2_String_String_Color(godot_method_bind *mb, godot_object *inst, const Object *, const Vector2& , const String& , const String& , const Color& );
int ___godot_icall_int_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
void ___godot_icall_void_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
Transform2D ___godot_icall_Transform2D_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
Vector2 ___godot_icall_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
Array ___godot_icall_Array(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_String_Object_int(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const int );
PoolStringArray ___godot_icall_PoolStringArray_String(godot_method_bind *mb, godot_object *inst, const String& );
PoolIntArray ___godot_icall_PoolIntArray_int_float_float(godot_method_bind *mb, godot_object *inst, const int , const float , const float );
godot_object*  ___godot_icall_Object_NodePath(godot_method_bind *mb, godot_object *inst, const NodePath& );
void ___godot_icall_void_PoolVector3Array_bool_bool(godot_method_bind *mb, godot_object *inst, const PoolVector3Array& , const bool , const bool );
void ___godot_icall_void_PoolIntArray(godot_method_bind *mb, godot_object *inst, const PoolIntArray& );
Array ___godot_icall_Array_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
Rect3 ___godot_icall_Rect3(godot_method_bind *mb, godot_object *inst);
PoolIntArray ___godot_icall_PoolIntArray_int(godot_method_bind *mb, godot_object *inst, const int );
Variant ___godot_icall_Variant_String_String_Variant(godot_method_bind *mb, godot_object *inst, const String& , const String& , const Variant& );
bool ___godot_icall_bool_float(godot_method_bind *mb, godot_object *inst, const float );
bool ___godot_icall_bool_String_InputEvent(godot_method_bind *mb, godot_object *inst, const String& , const InputEvent& );
void ___godot_icall_void_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
int ___godot_icall_int_int_int_int(godot_method_bind *mb, godot_object *inst, const int , const int , const int );
void ___godot_icall_void_PoolVector2Array_PoolColorArray_PoolVector2Array_Object_float(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& , const PoolColorArray& , const PoolVector2Array& , const Object *, const float );
void ___godot_icall_void_Object_int(godot_method_bind *mb, godot_object *inst, const Object *, const int );
PoolVector2Array ___godot_icall_PoolVector2Array_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_Vector3_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Vector3& );
void ___godot_icall_void_PoolVector2Array(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& );
bool ___godot_icall_bool_RID_Transform2D_Vector2_float_Object(godot_method_bind *mb, godot_object *inst, const RID& , const Transform2D& , const Vector2& , const float , const Object *);
void ___godot_icall_void_float_bool(godot_method_bind *mb, godot_object *inst, const float , const bool );
int ___godot_icall_int_RID(godot_method_bind *mb, godot_object *inst, const RID& );
int ___godot_icall_int_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
PoolByteArray ___godot_icall_PoolByteArray_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_RID_Transform(godot_method_bind *mb, godot_object *inst, const RID& , const Transform& );
Transform2D ___godot_icall_Transform2D_Object(godot_method_bind *mb, godot_object *inst, const Object *);
bool ___godot_icall_bool_Object_InputEvent(godot_method_bind *mb, godot_object *inst, const Object *, const InputEvent& );
Vector2 ___godot_icall_Vector2_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
PoolIntArray ___godot_icall_PoolIntArray_String_int_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int , const int );
void ___godot_icall_void_Array(godot_method_bind *mb, godot_object *inst, const Array& );
PoolVector2Array ___godot_icall_PoolVector2Array_Vector2_Vector2_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& , const Vector2& );
PoolVector2Array ___godot_icall_PoolVector2Array_int_float(godot_method_bind *mb, godot_object *inst, const int , const float );
String ___godot_icall_String_String_String_bool_int_int(godot_method_bind *mb, godot_object *inst, const String& , const String& , const bool , const int , const int );
void ___godot_icall_void_Vector3_float(godot_method_bind *mb, godot_object *inst, const Vector3& , const float );
void ___godot_icall_void_Vector2_int_bool_bool_bool(godot_method_bind *mb, godot_object *inst, const Vector2& , const int , const bool , const bool , const bool );
void ___godot_icall_void_int_int_Rect2_Vector2_float(godot_method_bind *mb, godot_object *inst, const int , const int , const Rect2& , const Vector2& , const float );
Dictionary ___godot_icall_Dictionary_PoolVector2Array(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& );
RID ___godot_icall_RID_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
Error ___godot_icall_Error_PoolByteArray(godot_method_bind *mb, godot_object *inst, const PoolByteArray& );
void ___godot_icall_void_String_NodePath_bool(godot_method_bind *mb, godot_object *inst, const String& , const NodePath& , const bool );
int ___godot_icall_int_String_Object_int(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const int );
float ___godot_icall_float_String(godot_method_bind *mb, godot_object *inst, const String& );
void ___godot_icall_void_int_Image(godot_method_bind *mb, godot_object *inst, const int , const Image& );
void ___godot_icall_void_String_Vector2(godot_method_bind *mb, godot_object *inst, const String& , const Vector2& );
int ___godot_icall_int_Object(godot_method_bind *mb, godot_object *inst, const Object *);
Error ___godot_icall_Error_String_int_bool_bool(godot_method_bind *mb, godot_object *inst, const String& , const int , const bool , const bool );
Dictionary ___godot_icall_Dictionary_int(godot_method_bind *mb, godot_object *inst, const int );
Vector3 ___godot_icall_Vector3_Vector3_Vector3_bool(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const bool );
godot_object*  ___godot_icall_Object_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
godot_object*  ___godot_icall_Object_String_String_bool(godot_method_bind *mb, godot_object *inst, const String& , const String& , const bool );
void ___godot_icall_void_int_int_Vector2(godot_method_bind *mb, godot_object *inst, const int , const int , const Vector2& );
int ___godot_icall_int_String_Object_String_Array_int(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const String& , const Array& , const int );
int ___godot_icall_int_String(godot_method_bind *mb, godot_object *inst, const String& );
Vector2 ___godot_icall_Vector2_float_bool(godot_method_bind *mb, godot_object *inst, const float , const bool );
Error ___godot_icall_Error_Object(godot_method_bind *mb, godot_object *inst, const Object *);
void ___godot_icall_void_int_Plane(godot_method_bind *mb, godot_object *inst, const int , const Plane& );
bool ___godot_icall_bool_Object_String_Object_String_Variant_float_int_int_float(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const Object *, const String& , const Variant& , const float , const int , const int , const float );
void ___godot_icall_void_Object_Transform2D(godot_method_bind *mb, godot_object *inst, const Object *, const Transform2D& );
void ___godot_icall_void_Plane(godot_method_bind *mb, godot_object *inst, const Plane& );
float ___godot_icall_float_RID_Vector2_int_int_Color(godot_method_bind *mb, godot_object *inst, const RID& , const Vector2& , const int , const int , const Color& );
void ___godot_icall_void_int_Color(godot_method_bind *mb, godot_object *inst, const int , const Color& );
void ___godot_icall_void_int_Array_Array_int(godot_method_bind *mb, godot_object *inst, const int , const Array& , const Array& , const int );
Dictionary ___godot_icall_Dictionary_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
void ___godot_icall_void_int_String_int(godot_method_bind *mb, godot_object *inst, const int , const String& , const int );
void ___godot_icall_void_PoolVector3Array_PoolVector2Array_PoolColorArray_PoolVector2Array_PoolVector3Array_Array(godot_method_bind *mb, godot_object *inst, const PoolVector3Array& , const PoolVector2Array& , const PoolColorArray& , const PoolVector2Array& , const PoolVector3Array& , const Array& );
float ___godot_icall_float(godot_method_bind *mb, godot_object *inst);
int ___godot_icall_int_String_String_int(godot_method_bind *mb, godot_object *inst, const String& , const String& , const int );
Array ___godot_icall_Array_Vector2_int_Array_int_int(godot_method_bind *mb, godot_object *inst, const Vector2& , const int , const Array& , const int , const int );
void ___godot_icall_void_String_int_Object_Vector2(godot_method_bind *mb, godot_object *inst, const String& , const int , const Object *, const Vector2& );
void ___godot_icall_void_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& );
int ___godot_icall_int_Object_Transform2D_Object(godot_method_bind *mb, godot_object *inst, const Object *, const Transform2D& , const Object *);
void ___godot_icall_void_RID_Rect2_bool_Color_bool(godot_method_bind *mb, godot_object *inst, const RID& , const Rect2& , const bool , const Color& , const bool );
void ___godot_icall_void_RID(godot_method_bind *mb, godot_object *inst, const RID& );
void ___godot_icall_void_RID_RID(godot_method_bind *mb, godot_object *inst, const RID& , const RID& );
PoolVector3Array ___godot_icall_PoolVector3Array(godot_method_bind *mb, godot_object *inst);
Variant ___godot_icall_Variant_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_RID_Object_String_Variant(godot_method_bind *mb, godot_object *inst, const RID& , const Object *, const String& , const Variant& );
Vector2 ___godot_icall_Vector2_Vector2_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& );
godot_object*  ___godot_icall_Object_RID(godot_method_bind *mb, godot_object *inst, const RID& );
Variant ___godot_icall_Variant_String(godot_method_bind *mb, godot_object *inst, const String& );
Rect2 ___godot_icall_Rect2_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_int_Variant_bool(godot_method_bind *mb, godot_object *inst, const int , const Variant& , const bool );
String ___godot_icall_String_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int );
bool ___godot_icall_bool_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_Object_Object_String_Variant(godot_method_bind *mb, godot_object *inst, const Object *, const Object *, const String& , const Variant& );
Error ___godot_icall_Error_String_int_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const String& , const int );
void ___godot_icall_void_int_String_String_Variant(godot_method_bind *mb, godot_object *inst, const int , const String& , const String& , const Variant& );
NodePath ___godot_icall_NodePath_int(godot_method_bind *mb, godot_object *inst, const int );
String ___godot_icall_String_Variant(godot_method_bind *mb, godot_object *inst, const Variant& );
void ___godot_icall_void_RID_int_Transform2D(godot_method_bind *mb, godot_object *inst, const RID& , const int , const Transform2D& );
void ___godot_icall_void_PoolVector2Array_PoolIntArray(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& , const PoolIntArray& );
int ___godot_icall_int_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
void ___godot_icall_void_int_float_Variant_float(godot_method_bind *mb, godot_object *inst, const int , const float , const Variant& , const float );
void ___godot_icall_void_bool_bool_int_int(godot_method_bind *mb, godot_object *inst, const bool , const bool , const int , const int );
Error ___godot_icall_Error(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_String(godot_method_bind *mb, godot_object *inst, const String& );
Vector3 ___godot_icall_Vector3_float(godot_method_bind *mb, godot_object *inst, const float );
void ___godot_icall_void_PoolColorArray(godot_method_bind *mb, godot_object *inst, const PoolColorArray& );
void ___godot_icall_void_int_Color_bool(godot_method_bind *mb, godot_object *inst, const int , const Color& , const bool );
Dictionary ___godot_icall_Dictionary_Vector2_Vector2_Array_int_int(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Array& , const int , const int );
int ___godot_icall_int_String_int_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int , const int );
void ___godot_icall_void_String_Array(godot_method_bind *mb, godot_object *inst, const String& , const Array& );
Array ___godot_icall_Array_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_int_int_int_int(godot_method_bind *mb, godot_object *inst, const int , const int , const int , const int );
PoolStringArray ___godot_icall_PoolStringArray_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_Rect2_bool(godot_method_bind *mb, godot_object *inst, const Rect2& , const bool );
godot_object*  ___godot_icall_Object_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
void ___godot_icall_void_PoolVector3Array(godot_method_bind *mb, godot_object *inst, const PoolVector3Array& );
Array ___godot_icall_Array_Object_int(godot_method_bind *mb, godot_object *inst, const Object *, const int );
void ___godot_icall_void_String_Object_bool(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const bool );
bool ___godot_icall_bool_Transform2D_Vector2(godot_method_bind *mb, godot_object *inst, const Transform2D& , const Vector2& );
void ___godot_icall_void_Object_Vector2(godot_method_bind *mb, godot_object *inst, const Object *, const Vector2& );
void ___godot_icall_void_PoolByteArray(godot_method_bind *mb, godot_object *inst, const PoolByteArray& );
void ___godot_icall_void_RID_Variant(godot_method_bind *mb, godot_object *inst, const RID& , const Variant& );
void ___godot_icall_void_RID_int_Variant(godot_method_bind *mb, godot_object *inst, const RID& , const int , const Variant& );
void ___godot_icall_void_Dictionary(godot_method_bind *mb, godot_object *inst, const Dictionary& );
void ___godot_icall_void_RID_int_RID(godot_method_bind *mb, godot_object *inst, const RID& , const int , const RID& );
void ___godot_icall_void_Variant(godot_method_bind *mb, godot_object *inst, const Variant& );
void ___godot_icall_void_RID_int_bool(godot_method_bind *mb, godot_object *inst, const RID& , const int , const bool );
Dictionary ___godot_icall_Dictionary_Vector3_Vector3_Array_int_int(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Array& , const int , const int );
void ___godot_icall_void_int_Transform2D(godot_method_bind *mb, godot_object *inst, const int , const Transform2D& );
void ___godot_icall_void_Vector2_Vector2_Color_float_bool(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Color& , const float , const bool );
bool ___godot_icall_bool_String_String(godot_method_bind *mb, godot_object *inst, const String& , const String& );
void ___godot_icall_void_RID_Vector2(godot_method_bind *mb, godot_object *inst, const RID& , const Vector2& );
void ___godot_icall_void_Object_bool_RID(godot_method_bind *mb, godot_object *inst, const Object *, const bool , const RID& );
void ___godot_icall_void_String_Object_String(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const String& );
int ___godot_icall_int_Vector2_Object(godot_method_bind *mb, godot_object *inst, const Vector2& , const Object *);
void ___godot_icall_void_int_int_int(godot_method_bind *mb, godot_object *inst, const int , const int , const int );
void ___godot_icall_void_Object_String_Variant(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const Variant& );
Array ___godot_icall_Array_float_float_int_int_int(godot_method_bind *mb, godot_object *inst, const float , const float , const int , const int , const int );
void ___godot_icall_void_float_float_float(godot_method_bind *mb, godot_object *inst, const float , const float , const float );
int ___godot_icall_int_int_float_bool(godot_method_bind *mb, godot_object *inst, const int , const float , const bool );
void ___godot_icall_void_int_int_int_bool_bool_bool(godot_method_bind *mb, godot_object *inst, const int , const int , const int , const bool , const bool , const bool );
bool ___godot_icall_bool_InputEvent_String(godot_method_bind *mb, godot_object *inst, const InputEvent& , const String& );
void ___godot_icall_void_String_String_float(godot_method_bind *mb, godot_object *inst, const String& , const String& , const float );
void ___godot_icall_void_int_Transform(godot_method_bind *mb, godot_object *inst, const int , const Transform& );
void ___godot_icall_void_Rect2(godot_method_bind *mb, godot_object *inst, const Rect2& );
void ___godot_icall_void_Vector2_Vector2_Vector2_int(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& , const int );
godot_object*  ___godot_icall_Object(godot_method_bind *mb, godot_object *inst);
Vector2 ___godot_icall_Vector2_int(godot_method_bind *mb, godot_object *inst, const int );
int ___godot_icall_int_Variant(godot_method_bind *mb, godot_object *inst, const Variant& );
Error ___godot_icall_Error_int_String_int(godot_method_bind *mb, godot_object *inst, const int , const String& , const int );
void ___godot_icall_void_Object_String_Array(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const Array& );
Color ___godot_icall_Color_float(godot_method_bind *mb, godot_object *inst, const float );
PoolVector3Array ___godot_icall_PoolVector3Array_Vector3_Vector3_float_float(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const float , const float );
void ___godot_icall_void_int_Vector2(godot_method_bind *mb, godot_object *inst, const int , const Vector2& );
void ___godot_icall_void_bool_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const bool , const Vector2& , const Vector2& );
bool ___godot_icall_bool_Vector2_float_Object(godot_method_bind *mb, godot_object *inst, const Vector2& , const float , const Object *);
Rect3 ___godot_icall_Rect3_int(godot_method_bind *mb, godot_object *inst, const int );
PoolVector3Array ___godot_icall_PoolVector3Array_int_float(godot_method_bind *mb, godot_object *inst, const int , const float );
RID ___godot_icall_RID_Image_int(godot_method_bind *mb, godot_object *inst, const Image& , const int );
bool ___godot_icall_bool_InputEvent(godot_method_bind *mb, godot_object *inst, const InputEvent& );
bool ___godot_icall_bool(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_String_int_Object(godot_method_bind *mb, godot_object *inst, const String& , const int , const Object *);
Vector3 ___godot_icall_Vector3_int_float(godot_method_bind *mb, godot_object *inst, const int , const float );
int ___godot_icall_int_NodePath(godot_method_bind *mb, godot_object *inst, const NodePath& );
void ___godot_icall_void_int_int_int_int_int(godot_method_bind *mb, godot_object *inst, const int , const int , const int , const int , const int );
void ___godot_icall_void_Object_String_int_int(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const int , const int );
void ___godot_icall_void_int_bool(godot_method_bind *mb, godot_object *inst, const int , const bool );
void ___godot_icall_void_PoolVector2Array_Color_PoolVector2Array_Object(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& , const Color& , const PoolVector2Array& , const Object *);
RID ___godot_icall_RID(godot_method_bind *mb, godot_object *inst);
int ___godot_icall_int_String_PoolStringArray_bool_Array(godot_method_bind *mb, godot_object *inst, const String& , const PoolStringArray& , const bool , const Array& );
Vector3 ___godot_icall_Vector3_float_bool(godot_method_bind *mb, godot_object *inst, const float , const bool );
void ___godot_icall_void_String_int_String(godot_method_bind *mb, godot_object *inst, const String& , const int , const String& );
Error ___godot_icall_Error_Object_bool_String(godot_method_bind *mb, godot_object *inst, const Object *, const bool , const String& );
bool ___godot_icall_bool_Object_String_Variant_Variant_float_int_int_float(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const Variant& , const Variant& , const float , const int , const int , const float );
godot_object*  ___godot_icall_Object_int(godot_method_bind *mb, godot_object *inst, const int );
Variant ___godot_icall_Variant_String_Array(godot_method_bind *mb, godot_object *inst, const String& , const Array& );
bool ___godot_icall_bool_String_String_bool(godot_method_bind *mb, godot_object *inst, const String& , const String& , const bool );
Vector2 ___godot_icall_Vector2_Vector2_bool(godot_method_bind *mb, godot_object *inst, const Vector2& , const bool );
void ___godot_icall_void_RID_Vector3(godot_method_bind *mb, godot_object *inst, const RID& , const Vector3& );
void ___godot_icall_void_int_int_float(godot_method_bind *mb, godot_object *inst, const int , const int , const float );
int ___godot_icall_int_String_PoolStringArray_bool_int_String(godot_method_bind *mb, godot_object *inst, const String& , const PoolStringArray& , const bool , const int , const String& );
void ___godot_icall_void_int_Array(godot_method_bind *mb, godot_object *inst, const int , const Array& );
bool ___godot_icall_bool_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& );
void ___godot_icall_void_RID_int_Transform(godot_method_bind *mb, godot_object *inst, const RID& , const int , const Transform& );
void ___godot_icall_void_String_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int );
void ___godot_icall_void_PoolVector3Array_Object_bool(godot_method_bind *mb, godot_object *inst, const PoolVector3Array& , const Object *, const bool );
void ___godot_icall_void_String_Object_String_Variant(godot_method_bind *mb, godot_object *inst, const String& , const Object *, const String& , const Variant& );
void ___godot_icall_void_String_Dictionary(godot_method_bind *mb, godot_object *inst, const String& , const Dictionary& );
void ___godot_icall_void_Object_InputEvent_Vector3_Vector3_int(godot_method_bind *mb, godot_object *inst, const Object *, const InputEvent& , const Vector3& , const Vector3& , const int );
void ___godot_icall_void_int_int_bool(godot_method_bind *mb, godot_object *inst, const int , const int , const bool );
void ___godot_icall_void_int(godot_method_bind *mb, godot_object *inst, const int );
NodePath ___godot_icall_NodePath(godot_method_bind *mb, godot_object *inst);
bool ___godot_icall_bool_String_int_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const String& , const int );
void ___godot_icall_void_Object_Rect2(godot_method_bind *mb, godot_object *inst, const Object *, const Rect2& );
RID ___godot_icall_RID_Vector2_Vector2_RID_RID(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const RID& , const RID& );
void ___godot_icall_void_Rect2_Color(godot_method_bind *mb, godot_object *inst, const Rect2& , const Color& );
godot_object*  ___godot_icall_Object_String_bool_String(godot_method_bind *mb, godot_object *inst, const String& , const bool , const String& );
void ___godot_icall_void_Object_Rect2_Rect2_Color_bool(godot_method_bind *mb, godot_object *inst, const Object *, const Rect2& , const Rect2& , const Color& , const bool );
Vector2 ___godot_icall_Vector2_RID(godot_method_bind *mb, godot_object *inst, const RID& );
Error ___godot_icall_Error_String(godot_method_bind *mb, godot_object *inst, const String& );
String ___godot_icall_String_Dictionary(godot_method_bind *mb, godot_object *inst, const Dictionary& );
Dictionary ___godot_icall_Dictionary(godot_method_bind *mb, godot_object *inst);
Transform2D ___godot_icall_Transform2D(godot_method_bind *mb, godot_object *inst);
PoolRealArray ___godot_icall_PoolRealArray_int(godot_method_bind *mb, godot_object *inst, const int );
PoolIntArray ___godot_icall_PoolIntArray_PoolVector2Array(godot_method_bind *mb, godot_object *inst, const PoolVector2Array& );
void ___godot_icall_void_int_PoolIntArray(godot_method_bind *mb, godot_object *inst, const int , const PoolIntArray& );
Color ___godot_icall_Color(godot_method_bind *mb, godot_object *inst);
godot_object*  ___godot_icall_Object_String_bool_bool(godot_method_bind *mb, godot_object *inst, const String& , const bool , const bool );
void ___godot_icall_void_String_String_Object_Object(godot_method_bind *mb, godot_object *inst, const String& , const String& , const Object *, const Object *);
void ___godot_icall_void_String_Variant(godot_method_bind *mb, godot_object *inst, const String& , const Variant& );
void ___godot_icall_void_Transform2D_Object(godot_method_bind *mb, godot_object *inst, const Transform2D& , const Object *);
void ___godot_icall_void_Object_InputEvent_int(godot_method_bind *mb, godot_object *inst, const Object *, const InputEvent& , const int );
Variant ___godot_icall_Variant(godot_method_bind *mb, godot_object *inst);
int ___godot_icall_int_int_Rect3(godot_method_bind *mb, godot_object *inst, const int , const Rect3& );
int ___godot_icall_int_int_String_PoolStringArray_PoolByteArray(godot_method_bind *mb, godot_object *inst, const int , const String& , const PoolStringArray& , const PoolByteArray& );
void ___godot_icall_void_RID_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const RID& , const Vector3& , const Vector3& );
int ___godot_icall_int_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
Error ___godot_icall_Error_Variant(godot_method_bind *mb, godot_object *inst, const Variant& );
void ___godot_icall_void_Object_Object(godot_method_bind *mb, godot_object *inst, const Object *, const Object *);
bool ___godot_icall_bool_Object_String_Variant_Object_String_float_int_int_float(godot_method_bind *mb, godot_object *inst, const Object *, const String& , const Variant& , const Object *, const String& , const float , const int , const int , const float );
float ___godot_icall_float_Vector2_Vector2_Vector2_float(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& , const float );
void ___godot_icall_void_int_float_float_float(godot_method_bind *mb, godot_object *inst, const int , const float , const float , const float );
bool ___godot_icall_bool_Vector2_Variant(godot_method_bind *mb, godot_object *inst, const Vector2& , const Variant& );
bool ___godot_icall_bool_Vector2_Vector2_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& , const Vector2& );
void ___godot_icall_void_RID_Transform2D(godot_method_bind *mb, godot_object *inst, const RID& , const Transform2D& );
String ___godot_icall_String(godot_method_bind *mb, godot_object *inst);
int ___godot_icall_int_String_int_String(godot_method_bind *mb, godot_object *inst, const String& , const int , const String& );
PoolIntArray ___godot_icall_PoolIntArray_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
PoolVector2Array ___godot_icall_PoolVector2Array(godot_method_bind *mb, godot_object *inst);
Variant ___godot_icall_Variant_Transform2D_Object_Transform2D(godot_method_bind *mb, godot_object *inst, const Transform2D& , const Object *, const Transform2D& );
PoolVector2Array ___godot_icall_PoolVector2Array_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& );
bool ___godot_icall_bool_String_int_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int , const int );
String ___godot_icall_String_int(godot_method_bind *mb, godot_object *inst, const int );
Transform ___godot_icall_Transform_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_int_String(godot_method_bind *mb, godot_object *inst, const int , const String& );
void ___godot_icall_void_InputEvent(godot_method_bind *mb, godot_object *inst, const InputEvent& );
Color ___godot_icall_Color_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
PoolByteArray ___godot_icall_PoolByteArray_String(godot_method_bind *mb, godot_object *inst, const String& );
void ___godot_icall_void_String_bool(godot_method_bind *mb, godot_object *inst, const String& , const bool );
godot_object*  ___godot_icall_Object_bool(godot_method_bind *mb, godot_object *inst, const bool );
Vector3 ___godot_icall_Vector3_int(godot_method_bind *mb, godot_object *inst, const int );
void ___godot_icall_void_RID_float(godot_method_bind *mb, godot_object *inst, const RID& , const float );
bool ___godot_icall_bool_RID(godot_method_bind *mb, godot_object *inst, const RID& );
void ___godot_icall_void_String_Object(godot_method_bind *mb, godot_object *inst, const String& , const Object *);
PoolStringArray ___godot_icall_PoolStringArray(godot_method_bind *mb, godot_object *inst);
bool ___godot_icall_bool_String_int_int_int_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const int , const int , const int );
void ___godot_icall_void_RID_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const RID& , const Vector2& , const Vector2& );
Plane ___godot_icall_Plane(godot_method_bind *mb, godot_object *inst);
int ___godot_icall_int_String_float_String_String(godot_method_bind *mb, godot_object *inst, const String& , const float , const String& , const String& );
Vector3 ___godot_icall_Vector3_RID(godot_method_bind *mb, godot_object *inst, const RID& );
PoolVector2Array ___godot_icall_PoolVector2Array_Vector2_Vector2_bool(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const bool );
bool ___godot_icall_bool_int_int(godot_method_bind *mb, godot_object *inst, const int , const int );
int ___godot_icall_int_String_int_PoolByteArray(godot_method_bind *mb, godot_object *inst, const String& , const int , const PoolByteArray& );
godot_object*  ___godot_icall_Object_String(godot_method_bind *mb, godot_object *inst, const String& );
Transform2D ___godot_icall_Transform2D_RID(godot_method_bind *mb, godot_object *inst, const RID& );
Dictionary ___godot_icall_Dictionary_String(godot_method_bind *mb, godot_object *inst, const String& );
void ___godot_icall_void_int_Rect2(godot_method_bind *mb, godot_object *inst, const int , const Rect2& );
Vector2 ___godot_icall_Vector2_Vector2_Vector2_float_int_float(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const float , const int , const float );
void ___godot_icall_void_Vector2_Vector2_Vector2_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Vector2& , const Vector2& , const Vector2& );
bool ___godot_icall_bool_Vector2_Rect2(godot_method_bind *mb, godot_object *inst, const Vector2& , const Rect2& );
PoolIntArray ___godot_icall_PoolIntArray(godot_method_bind *mb, godot_object *inst);
void ___godot_icall_void_PoolStringArray(godot_method_bind *mb, godot_object *inst, const PoolStringArray& );
void ___godot_icall_void_Transform2D(godot_method_bind *mb, godot_object *inst, const Transform2D& );
Transform ___godot_icall_Transform_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
void ___godot_icall_void_float(godot_method_bind *mb, godot_object *inst, const float );
void ___godot_icall_void_int_String_String(godot_method_bind *mb, godot_object *inst, const int , const String& , const String& );
Vector2 ___godot_icall_Vector2_int_float(godot_method_bind *mb, godot_object *inst, const int , const float );
float ___godot_icall_float_Vector2(godot_method_bind *mb, godot_object *inst, const Vector2& );
void ___godot_icall_void_int_int_float_bool(godot_method_bind *mb, godot_object *inst, const int , const int , const float , const bool );
Transform ___godot_icall_Transform(godot_method_bind *mb, godot_object *inst);
RID ___godot_icall_RID_Vector2_RID_RID(godot_method_bind *mb, godot_object *inst, const Vector2& , const RID& , const RID& );
void ___godot_icall_void_Object_String(godot_method_bind *mb, godot_object *inst, const Object *, const String& );
int ___godot_icall_int_int_String(godot_method_bind *mb, godot_object *inst, const int , const String& );
void ___godot_icall_void_String_float(godot_method_bind *mb, godot_object *inst, const String& , const float );
bool ___godot_icall_bool_RID_int(godot_method_bind *mb, godot_object *inst, const RID& , const int );
bool ___godot_icall_bool_Transform2D_Object_Transform2D(godot_method_bind *mb, godot_object *inst, const Transform2D& , const Object *, const Transform2D& );
Vector3 ___godot_icall_Vector3_Vector3_Vector3_Vector3(godot_method_bind *mb, godot_object *inst, const Vector3& , const Vector3& , const Vector3& );
void ___godot_icall_void_String_String_Variant(godot_method_bind *mb, godot_object *inst, const String& , const String& , const Variant& );
void ___godot_icall_void_Object_int_bool(godot_method_bind *mb, godot_object *inst, const Object *, const int , const bool );
void ___godot_icall_void_String_int_String_int(godot_method_bind *mb, godot_object *inst, const String& , const int , const String& , const int );
void ___godot_icall_void_Vector2_float_Color(godot_method_bind *mb, godot_object *inst, const Vector2& , const float , const Color& );
void ___godot_icall_void_Vector2_Variant(godot_method_bind *mb, godot_object *inst, const Vector2& , const Variant& );
void ___godot_icall_void_int_PoolRealArray(godot_method_bind *mb, godot_object *inst, const int , const PoolRealArray& );
#endif